server:
  port: 6000

spring:
  application:
    name: campagnes
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables service discovery
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
