server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # Do not register this instance with itself or any other Eureka server
    fetch-registry: false        # Do not fetch registry from other Eureka instances
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false  # Optional: Disables self-preservation mode to avoid heartbeat issues
    wait-time-in-ms-when-sync-empty: 0

spring:
  application:
    name: eureka-server
